// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using online_corse.Models;

#nullable disable

namespace online_corse.Migrations
{
    [DbContext(typeof(OnlineCoursesContext))]
    [Migration("20240617204643_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("online_corse.Models.Corse", b =>
                {
                    b.Property<int>("CorseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CorseId"), 1L, 1);

                    b.Property<string>("CorseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CosrePrice")
                        .HasColumnType("int");

                    b.HasKey("CorseId");

                    b.ToTable("Corses");

                    b.HasData(
                        new
                        {
                            CorseId = 1,
                            CorseName = "C++",
                            CosrePrice = 150
                        },
                        new
                        {
                            CorseId = 2,
                            CorseName = "V&V",
                            CosrePrice = 60
                        },
                        new
                        {
                            CorseId = 3,
                            CorseName = "Math",
                            CosrePrice = 80
                        },
                        new
                        {
                            CorseId = 4,
                            CorseName = "Web Programming",
                            CosrePrice = 300
                        },
                        new
                        {
                            CorseId = 5,
                            CorseName = "Embeded System",
                            CosrePrice = 190
                        },
                        new
                        {
                            CorseId = 6,
                            CorseName = "Java",
                            CosrePrice = 160
                        },
                        new
                        {
                            CorseId = 7,
                            CorseName = "English",
                            CosrePrice = 90
                        },
                        new
                        {
                            CorseId = 8,
                            CorseName = "Arabic",
                            CosrePrice = 90
                        },
                        new
                        {
                            CorseId = 9,
                            CorseName = "Python",
                            CosrePrice = 130
                        },
                        new
                        {
                            CorseId = 10,
                            CorseName = "Project Managment",
                            CosrePrice = 110
                        });
                });

            modelBuilder.Entity("online_corse.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"), 1L, 1);

                    b.Property<double>("Average")
                        .HasColumnType("float");

                    b.Property<int>("CorseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("CorseId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Average = 92.0,
                            CorseId = 1,
                            Name = "Ahmad",
                            Password = "123"
                        },
                        new
                        {
                            StudentId = 2,
                            Average = 99.0,
                            CorseId = 1,
                            Name = "Aya",
                            Password = "212"
                        },
                        new
                        {
                            StudentId = 3,
                            Average = 97.0,
                            CorseId = 6,
                            Name = "Hala",
                            Password = "262"
                        },
                        new
                        {
                            StudentId = 4,
                            Average = 89.0,
                            CorseId = 4,
                            Name = "Saba",
                            Password = "762"
                        },
                        new
                        {
                            StudentId = 5,
                            Average = 97.0,
                            CorseId = 7,
                            Name = "Rawan",
                            Password = "292"
                        },
                        new
                        {
                            StudentId = 6,
                            Average = 74.0,
                            CorseId = 2,
                            Name = "Noor",
                            Password = "202"
                        },
                        new
                        {
                            StudentId = 7,
                            Average = 97.0,
                            CorseId = 3,
                            Name = "Raghad",
                            Password = "202"
                        },
                        new
                        {
                            StudentId = 8,
                            Average = 67.0,
                            CorseId = 3,
                            Name = "Zaid",
                            Password = "162"
                        },
                        new
                        {
                            StudentId = 9,
                            Average = 88.0,
                            CorseId = 3,
                            Name = "Mohammed",
                            Password = "200"
                        },
                        new
                        {
                            StudentId = 10,
                            Average = 57.0,
                            CorseId = 2,
                            Name = "Tawfiq",
                            Password = "772"
                        },
                        new
                        {
                            StudentId = 11,
                            Average = 91.0,
                            CorseId = 2,
                            Name = "Suha",
                            Password = "779"
                        });
                });

            modelBuilder.Entity("online_corse.Models.Student", b =>
                {
                    b.HasOne("online_corse.Models.Corse", "Corse")
                        .WithMany()
                        .HasForeignKey("CorseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corse");
                });
#pragma warning restore 612, 618
        }
    }
}
