// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project.Models;

#nullable disable

namespace project.Migrations
{
    [DbContext(typeof(BuyContext))]
    [Migration("20240930155755_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("project.Models.Piece", b =>
                {
                    b.Property<int>("PieceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PieceID"), 1L, 1);

                    b.Property<string>("PieceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Pieceprice")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PieceID");

                    b.HasIndex("UserId");

                    b.ToTable("Pieces");

                    b.HasData(
                        new
                        {
                            PieceID = 100,
                            PieceName = "Necklace Pendant and Earrings",
                            Pieceprice = 150f,
                            UserId = 1
                        },
                        new
                        {
                            PieceID = 101,
                            PieceName = "Silver Bracelet",
                            Pieceprice = 120f,
                            UserId = 2
                        },
                        new
                        {
                            PieceID = 102,
                            PieceName = "Gold Ring with Diamonds",
                            Pieceprice = 100f,
                            UserId = 3
                        },
                        new
                        {
                            PieceID = 103,
                            PieceName = "Pendant Necklace and Earrings",
                            Pieceprice = 180f,
                            UserId = 3
                        },
                        new
                        {
                            PieceID = 104,
                            PieceName = "Silver and Gold Necklace",
                            Pieceprice = 140f,
                            UserId = 3
                        },
                        new
                        {
                            PieceID = 105,
                            PieceName = "Floral Ring with Diamonds",
                            Pieceprice = 180f,
                            UserId = 2
                        },
                        new
                        {
                            PieceID = 106,
                            PieceName = "Silver Bracelet",
                            Pieceprice = 150f,
                            UserId = 2
                        },
                        new
                        {
                            PieceID = 107,
                            PieceName = "Silver Ring with Diamonds",
                            Pieceprice = 100f,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("project.Models.user", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Password = "ahmad123",
                            UserEmail = "ahmad@gmail.com",
                            UserName = "ahmad"
                        },
                        new
                        {
                            UserId = 2,
                            Password = "omar123",
                            UserEmail = "omar@gmail.com",
                            UserName = "omar"
                        },
                        new
                        {
                            UserId = 3,
                            Password = "Mohammad123",
                            UserEmail = "Mohammad@gmail.com",
                            UserName = "Mohammad"
                        },
                        new
                        {
                            UserId = 4,
                            Password = "0000",
                            UserEmail = "jewellary@gmail.com",
                            UserName = "jewellary"
                        });
                });

            modelBuilder.Entity("project.Models.Piece", b =>
                {
                    b.HasOne("project.Models.user", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
